name: Build & Test (on Feature/Hotfix PRs)
on: push
jobs:
  test-everywhere:
    name: Test Action on all platforms
    runs-on: ubuntu-latest
    services:
      mssql:
        image: mcr.microsoft.com/mssql/server:2022-latest
        env:
          SA_PASSWORD: rootpassword
          ACCEPT_EULA: 'Y'
        ports:
          - 21433:1433

    steps:
      - uses: actions/checkout@v3

      - name: Run the action
        uses: potatoqualitee/mssqlsuite@v1.7
        with:
          install: sqlengine, sqlpackage

      - name: Run sqlclient
        run: sqlcmd -S localhost -U sa -P dbatools.I0 -d tempdb -Q "SELECT @@version;"

      - name: check if docker is worked
        run: docker ps
        
